application: lovely-io
version:     1_0_0
runtime:     python
api_version: 1


handlers:
# the index page routes
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /index.css
  static_files: static/index.css
  upload: static/index.css

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
